name: Second Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List file
        run: |
         pwd
         ls -a
         - uses: actions/checkout@v5
      - name: list file and copy repo
        run: ls -a